# Generated by Django 5.0.6 on 2024-07-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0002_adoptcatpics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adoptbirdpics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birdname', models.CharField(max_length=15)),
                ('birddesc', models.CharField(max_length=100)),
                ('birdimg', models.ImageField(upload_to='bird_pics')),
            ],
        ),
        migrations.CreateModel(
            name='Adoptsmallpetpics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smallpetname', models.CharField(max_length=15)),
                ('smallpetdesc', models.CharField(max_length=100)),
                ('smallpetimg', models.ImageField(upload_to='smallpet_pics')),
            ],
        ),
    ]
