# Generated by Django 5.0.6 on 2024-07-22 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_shipping_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipping_address',
            old_name='adderss',
            new_name='address',
        ),
    ]
