# Generated by Django 5.0.6 on 2024-07-25 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_order_date_shipped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_ordered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='date_shipped',
        ),
    ]
