# Generated by Django 5.0.6 on 2024-07-26 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_amount_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amount_paid',
            old_name='amount_img',
            new_name='payment_img',
        ),
    ]
