# Generated by Django 5.0.6 on 2024-07-26 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_rename_amount_img_amount_paid_payment_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amount_paid',
            old_name='payment_img',
            new_name='payment_image',
        ),
    ]
