# Generated by Django 5.0.6 on 2024-07-26 13:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_rename_payment_img_amount_paid_payment_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='amount_paid',
            new_name='AmountPaidPicture',
        ),
    ]
